### ISSUE TITLE
Is double check required

### ISSUE THREAD

**Issue by Truba** [infinum/app-deploy-script#1]
https://github.com/infinum/app-deploy-script/blob/1974bdfa44ebb5654f639633f1535e41e946a78b/app-deploy.sh#L257

Hi, I was thinking about your thoughts on this one. Do we really need that double check? This is something that we didn't have in the previous script. 
And I actually had an issue with this, that happened to me a few times. 
I filled in the log, and went on my marry way, only to figure out ~20-30 min later that my terminal is still waiting for me to approve the build 😆

**Comment by Truba** [comment]
What are your thoughts on the issue?

**Comment by jabou** [comment]
Initially I didn't have that, but after talking with few colleges in our team, they told me that this is useful for them so that they can check if everything is ok before tag is pushed/build triggered. Main idea is that sometimes you hit wrong deployment version (e.g. you want to deploy to `tryoutapps` but you have select `appstore` by mistake) or maybe you find spelling error or missing change in the changelog, etc.

When you look at the number of confirmation steps, number is same as before but only difference is that on first version confirmation was at the beginning (i.e. is this correct commit?), while now confirmation is at the end (is this correct configuration?)

Maybe we can add some configurations for steps at the beginning of the script, some flags? Something like `enableFinalConfirmation`, `enableAutomaticCommitPush`, `enableTagMessage`. By default, everything is enabled but you can turn on/off some steps without need to delete something from the script locally on your project. What do you think about that?

**Comment by jabou** [comment]
As agreed, we will go with the "flags" option. 
Available options will be: `enableFinalConfirmation` i `enableAutomaticCommitPush`

**Comment by jabou** [comment]
Resolved as part of #3 PR
